name: xlstmpt240cu124
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cuda=12.4
  - cuda-nvcc=12.4
  - gxx_linux-64=11.2.0
  - python=3.11
  - pip #=23.3.2
  - pytorch=2.4.0
  - pytorch-cuda=12.4
  - torchvision #=0.17.0
  - cmake #=3.28.2
  - cuda-cccl=12.4
  - cuda-toolkit=12.4
  - pip:
      - einops #==0.7.0
      - opt_einsum #==3.3.0
      - pre-commit #==3.6.0
      - reportlab #==4.0.9
      - ipykernel #==6.29.0
      - dacite #==1.8.1
      - ftfy #==6.1.3
      - ninja #==1.11.1.1
      - joblib #==1.3.2
      - tqdm #==4.66.1
      - pytest #==8.0.0
      - pytest-xdist #==3.5.0
      - cryptography #==42.0.2
      - matplotlib
      - numpy
      - pandas
